


export const cricketers =[
    { name: "Virat Kohli", team: "India", odiRuns: 12000, testRuns: 8000 },
    { name: "Steve Smith", team: "Australia", odiRuns: 5000, testRuns: 6000 },
    { name: "Kane Williamson", team: "New Zealand", odiRuns: 8000, testRuns: 7000 },
    { name: "Joe Root", team: "England", odiRuns: 6000, testRuns: 10000 },
    { name: "Babar Azam", team: "Pakistan", odiRuns: 4000, testRuns: 3000 },
    { name: "David Warner", team: "Australia", odiRuns: 7000, testRuns: 9000 },
    { name: "Rohit Sharma", team: "India", odiRuns: 10000, testRuns: 6000 },
    { name: "Kagiso Rabada", team: "South Africa", odiRuns: 500, testRuns: 1000 },
    { name: "Jasprit Bumrah", team: "India", odiRuns: 200, testRuns: 500 },
    { name: "Mitchell Starc", team: "Australia", odiRuns: 1000, testRuns: 2000 },
    { name: "Jason Holder", team: "West Indies", odiRuns: 2000, testRuns: 3000 },
    { name: "Ben Stokes", team: "England", odiRuns: 4000, testRuns: 5000 },
    { name: "Ross Taylor", team: "New Zealand", odiRuns: 8000, testRuns: 7000 },
    { name: "Shikhar Dhawan", team: "India", odiRuns: 5000, testRuns: 3000 },
    { name: "Marnus Labuschagne", team: "Australia", odiRuns: 1000, testRuns: 3000 },
    { name: "Rishabh Pant", team: "India", odiRuns: 2000, testRuns: 2000 },
    { name: "Pat Cummins", team: "Australia", odiRuns: 500, testRuns: 1000 },
    { name: "Quinton de Kock", team: "South Africa", odiRuns: 6000, testRuns: 4000 },
    { name: "Moeen Ali", team: "England", odiRuns: 3000, testRuns: 4000 },
    { name: "Usman Khawaja", team: "Australia", odiRuns: 2000, testRuns: 4000 },
    { name: "Kusal Perera", team: "Sri Lanka", odiRuns: 3000, testRuns: 2000 },
    { name: "Mohammad Amir", team: "Pakistan", odiRuns: 500, testRuns: 1000 },
    { name: "Mitchell Marsh", team: "Australia", odiRuns: 2000, testRuns: 1000 },
    {name: "Sachin Tendulkar", team: "India", odiRuns: 8494, testRuns: 7054},
    {name: "Ricky Ponting", team: "Australia", odiRuns: 6766, testRuns: 6709},
    {name: "Brian Lara", team: "West Indies", odiRuns: 5787, testRuns: 7737},
    {name: "Jacques Kallis", team: "South Africa", odiRuns: 6843, testRuns: 6716},
    {name: "Inzamam-ul-Haq", team: "Pakistan", odiRuns: 5019, testRuns: 5165},
    {name: "Sanath Jayasuriya", team: "Sri Lanka", odiRuns: 5819, testRuns: 3905},
    {name: "Steve Waugh", team: "Australia", odiRuns: 2277, testRuns: 3167},
    {name: "Muttiah Muralitharan", team: "Sri Lanka", odiRuns: 76, testRuns: 263},
    {name: "Adam Gilchrist", team: "Australia", odiRuns: 3467, testRuns: 3177},
    {name: "Shane Warne", team: "Australia", odiRuns: 173, testRuns: 538},
    {name: "Sourav Ganguly", team: "India", odiRuns: 3902, testRuns: 5038},
    {name: "Stephen Fleming", team: "New Zealand", odiRuns: 4014, testRuns: 3778},
    {name: "Shaun Pollock", team: "South Africa", odiRuns: 1941, testRuns: 1553},
    {name: "Chaminda Vaas", team: "Sri Lanka", odiRuns: 1443, testRuns: 1227},
    {name: "VVS Laxman", team: "India", odiRuns: 2354, testRuns: 2742},
    {name: "Graeme Smith", team: "South Africa", odiRuns: 3611, testRuns: 2561},
    {name: "Andrew Flintoff", team: "England", odiRuns: 2282, testRuns: 2285},
    {name: "Chris Cairns", team: "New Zealand", odiRuns: 1100, testRuns: 1436},
    {name: "Michael Vaughan", team: "England", odiRuns: 1742, testRuns: 3381},
    {name: "Herschelle Gibbs", team: "South Africa", odiRuns: 4706, testRuns: 3916},
    {name: "Matthew Hayden", team: "Australia", odiRuns: 3954, testRuns: 4965},
    {name: "Anil Kumble", team: "India", odiRuns: 166, testRuns: 710},
        
    
]  